package_reboot_if_required: true
packages:
  - apache2
  - cowsay
  - qemu-guest-agent
runcmd:
  - systemctl start qemu-guest-agent
  - systemctl enable qemu-guest-agent
  - echo "job done" >> /home/user/testing.txt