scrape_configs:
  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.2.10  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.2.11:9221  # PVE exporter IP address and port number - use docker host IP, not localhost
